[template.environment]
  AUTHOR_NAME = "Your Name"
  AUTHOR_EMAIL = "Your email address"
  SITE_NAME = "Website name"
  SITE_DESCRIPTION = "Website description"
  GITHUB_TOKEN = "Access token from Github"

[[plugins]]
package = "netlify-plugin-inline-functions-env"