[template.environment]
  AUTHOR_NAME = "Your Name"
  AUTHOR_EMAIL = "Your email address"
  SITE_NAME = "Website name"
  SITE_DESCRIPTION = "Website description"
  GITHUB_URL = "URL to your github repository"
  GITHUB_TOKEN = "Access token from Github"