[template.environment]
  AUTHOR_NAME = "Your Name"
  AUTHOR_EMAIL = "Your email address"
  SITE_TITLE = "Website name"
  SITE_DESCRIPTION = "Website description"
  GITHUB_TOKEN = "Access token from Github with 'repo' permissions"

[[plugins]]
package = "netlify-plugin-inline-functions-env"

[functions]
  directory = "functions/"

[[redirects]]
  from = "/11ndieweb/:function"
  to = "/.netlify/functions/11ndieweb"
  status = 200